limit: 5000000000000000

memory_size:
  instruction: 1000
  data: 1000

stack_size:
  ret: 1000
  data: 1000

io:
  outputs:
    default:
      kind: char
      address: 0x222
    int_output:
      kind: int
      address: 0x224
  inputs:
    keyboard:
      address: 0x223
      vector: 0
      schedule:
        - [1, h]
        - [100, e]
        - [200, l]
        - [250, l]
        - [1000, o]
