limit: 5000

memory_size:
  instruction: 1000
  data: 1000

stack_size:
  ret: 1000
  data: 1000

io:
  char_output:
    address: 0x222
  char_input:
    address: 0x223
    vector: 0
    schedule:
      - [1, h]
      - [100, e]
      - [200, l]
      - [250, l]
      - [1000, o]
