WORD_WIDTH = 32
WORD_MASK = (1 << WORD_WIDTH) - 1
SIGN_BIT = 1 << (WORD_WIDTH - 1)
MAX_SIGNED = (1 << (WORD_WIDTH - 1)) - 1
MIN_SIGNED = -(1 << (WORD_WIDTH - 1))

WORD_BYTES = WORD_WIDTH // 8
INSTR_BYTES = 8
