WORD_WIDTH = 32
WORD_BYTES = WORD_WIDTH // 8
WORD_MASK = (1 << WORD_WIDTH) - 1

SIGN_BIT = 1 << (WORD_WIDTH - 1)
MAX_SIGNED = (1 << (WORD_WIDTH - 1)) - 1
MIN_SIGNED = -(1 << (WORD_WIDTH - 1))

INSTR_WIDTH = 40
INSTR_BYTES = INSTR_WIDTH // 8

DWORD_WIDTH = 2 * WORD_WIDTH
DWORD_MASK = (1 << DWORD_WIDTH) - 1
DWORD_SIGN_BIT = 1 << (DWORD_WIDTH - 1)
DWORD_MAX_SIGNED = (1 << (DWORD_WIDTH - 1)) - 1
DWORD_MIN_SIGNED = -(1 << (DWORD_WIDTH - 1))
